//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialtyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArrearsLessons
    {
        public int Id { get; set; }
        public int IdArrear { get; set; }
        public int IdLesson { get; set; }
        public int IdType { get; set; }
        public bool IsLiquidated { get; set; }
        public bool IsGoodReason { get; set; }
    
        public virtual Arrears Arrears { get; set; }
        public virtual Lessons Lessons { get; set; }
        public virtual TypesArrears TypesArrears { get; set; }
    }
}
