//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpecialtyManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsPerformance
    {
        public int Id { get; set; }
        public int IdStudent { get; set; }
        public int NumberOfStudents { get; set; }
        public int NumberOfSuccessful { get; set; }
        public int NumberOfUnsuccessful { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
